/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.
===============================================================================
*/

-- Find total customers by countries
SELECT
country,
COUNT(customer_key) as total_customer 
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customer DESC;

-- Find total customers by gender
SELECT 
gender,
COUNT (customer_key) as total_customer 
FROM gold.dim_customers
GROUP BY gender 
order by total_customer; 

-- What is the average costs in each category?
SELECT 
category,
AVG(COST) as avg_cost 
FROM gold.dim_products
GROUP BY CATEGORY 
ORDER BY avg_cost DESC ;


-- What is the total revenue generated for each category?
SELECT 
p.category,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category 
order by total_revenue DESC 

 --What is the total revenue generated by each customer?
 SELECT 
 c.customer_key,
 C.first_name,
 c.last_name,
 SUM (f.sales_amount) as total_revenue
 FROM gold.dim_customers c
 LEFT JOIN gold.fact_sales f
 ON f.customer_key= c.customer_key
 GROUP BY c.customer_key,
 C.first_name,
 c.last_name
 ORDER BY total_revenue DESC 

